### PR TITLE
Fix mpv-write-title.lua has a problem with long records (#2)

### LINKED ISSUE #2: mpv-write-title.lua has a problem with long records
mpv-write-title.lua stop writing new tans to tarck_names.tanfmrr, if the track_names.tanfmrr file is to big.

### PR DESCRIPTION
**Pull request by rusty-snake**
This is a first try to fix #2.

Note that the `track_names.tanfmrr` creation process has to be revised again for #3.

### CODE REVIEW

File: mpv-write-title.lua [hunk 1]
```diff
@@ -1,10 +1,28 @@
+-- A comment starts in lua with a --
+
+-- load mp.utils
+local utils = require 'mp.utils'
+
+-- This function is called whenever the title changes.
+-- name can be ignored
+-- value contains the title
 function write_title(name, value)
 	if not (mp.get_property("duration") == nil) then
```
Comment (rusty-snake) [inline mpv-write-title.lua]: Why there is an `if`?

**Comment by rusty-snake** [comment]
This code fix definitely #2.

**Comment by rusty-snake** [comment]
Because at the moment here is no work and it fix a bug, it will be merged.
